
matrix:
    include:
        - os: osx
          language: shell
          env: PYTHON_VERSION=3.7.1
        - os: linux
          language: shell
          env: PYTHON_VERSION=3.7.1
        - os: windows
          language: shell
          env: PYTHON_VERSION=3.7.1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHON_VERSION && pyenv global $PYTHON_VERSION; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv install $PYTHON_VERSION && pyenv global $PYTHON_VERSION; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python --version $PYTHON_VERSION; fi

install:
    - python --version

script: echo hello
