jobs:
- job: 'Build_Linux'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - checkout: self
    submodules: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install --upgrade pip
    displayName: 'Install pipenv'
  - script: pip install pybind11 twine wheel
    displayName: 'Install dependencies'
  - script: python setup.py sdist
    displayName: 'Build source'
  - script: python setup.py bdist_wheel --universal
    displayName: 'Build binaries'


- job: 'Build_Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - checkout: self
    submodules: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x86'
  - script: python -m pip install --upgrade pip
    displayName: 'Install pipenv'
  - script: pip install pybind11 twine wheel pyfindvs
    displayName: 'Install dependencies'
  - script: python setup.py sdist
    displayName: 'Build source'
  - script: python setup.py bdist_wheel --universal
    displayName: 'Build binaries'
  - script: twine upload --skip-existing --repository deargui dist/*
    displayName: 'Upload to pypi'
    env:
      TWINE_USERNAME: $(twine.username)
      TWINE_PASSWORD: $(twine.password)


- job: 'Build_Mac'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - checkout: self
    submodules: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install --upgrade pip
    displayName: 'Install pipenv'
  - script: pip install pybind11 twine wheel
    displayName: 'Install dependencies'
  - script: python setup.py sdist
    displayName: 'Build source'
  - script: python setup.py bdist_wheel --universal
    displayName: 'Build binaries'
  - script: twine upload --skip-existing --repository deargui dist/*
    displayName: 'Upload to pypi'
    env:
      TWINE_USERNAME: $(twine.username)
      TWINE_PASSWORD: $(twine.password)
